<?php

namespace ImageBundle\Repository;

/**
 * ImageProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
