<?php

namespace HotelBundle\Repository;

/**
 * PhysicalRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysicalRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
