<?php

namespace HotelBundle\Repository;

/**
 * RoomMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
