<?php

namespace HotelBundle\Repository;

/**
 * RoomBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomBookingRepository extends \Doctrine\ORM\EntityRepository
{
}
