<?php

namespace HotelBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSetting($slug = 'default')
    {
        $qb =  $this->createQueryBuilder('s');
        $qb->andWhere('s.slug = :slug');
        $qb->setParameter('slug', $slug);
        $qb->setMaxResults(1);

        $setting = $qb->getQuery()->getSingleResult();

        return $setting;

    }


}
